name: Deployment Application
on:
  push:
    branches: [main]
jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
    - name: Get repository code
      uses: actions/checkout@v4
    - name: Cache npm dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('**/package-lock.json') }}
    - name: Installation of dependencies
      run: npm ci
    - name: Creating an environment file
      run: echo "REACT_APP_TOKEN = ${{secrets.token}}" >> .env
    - name: Building App for prodaction
      run: npm run build
    - name: Deployment App
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: ./build